#!/bin/sh
# Cut a GitHub release tag (canonical: micropy-system).
#
# Verifies the project repo is clean and in sync with origin, tags
# vMAJOR.MINOR.PATCH, and pushes the tag. The project's GitHub Actions
# workflow (release-firmware.yml, generated by tools/init_project.sh) then
# builds the firmware and publishes the GitHub release the boards can
# update from (update-source.json mode "github").
#
# Usage: tools/release_github.sh MAJOR.MINOR.PATCH [--app-root PATH]
set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
FRAMEWORK_ROOT=$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)

VERSION=""
APP_ROOT=""
PENDING=""
for arg in "$@"; do
    if [ -n "$PENDING" ]; then
        APP_ROOT="$arg"
        PENDING=""
        continue
    fi
    case "$arg" in
        --app-root) PENDING=approot ;;
        -h|--help)  sed -n '2,/^set -eu$/p' "$0" | sed '$d'; exit 0 ;;
        -*)         echo "Error: unknown argument '$arg' (try --help)" >&2; exit 2 ;;
        *)          VERSION="$arg" ;;
    esac
done

if [ -z "$APP_ROOT" ]; then
    APP_ROOT="${MICROPY_APP_ROOT:-}"
fi
if [ -z "$APP_ROOT" ]; then
    APP_ROOT=$(git -C "$FRAMEWORK_ROOT" rev-parse --show-superproject-working-tree 2>/dev/null || true)
fi
if [ -z "$APP_ROOT" ]; then
    APP_ROOT=$(pwd)
fi
APP_ROOT=$(CDPATH= cd -- "$APP_ROOT" && pwd)

if [ -z "$VERSION" ]; then
    echo "Usage: tools/release_github.sh MAJOR.MINOR.PATCH" >&2
    exit 2
fi
VERSION=${VERSION#v}
case "$VERSION" in
    *[!0-9.]*|*.*.*.*|.*|*.)
        echo "Error: version must have the form MAJOR.MINOR.PATCH" >&2
        exit 2
        ;;
esac
if [ "$(printf '%s' "$VERSION" | awk -F. '{print NF}')" -ne 3 ]; then
    echo "Error: version must have the form MAJOR.MINOR.PATCH" >&2
    exit 2
fi
TAG="v$VERSION"

if [ -n "$(git -C "$APP_ROOT" status --porcelain)" ]; then
    echo "Error: commit or stash application changes before releasing." >&2
    exit 1
fi
git -C "$APP_ROOT" fetch origin --tags
if git -C "$APP_ROOT" rev-parse -q --verify "refs/tags/$TAG" >/dev/null; then
    echo "Error: tag already exists: $TAG" >&2
    exit 1
fi

BRANCH=$(git -C "$APP_ROOT" branch --show-current)
if [ -z "$BRANCH" ]; then
    echo "Error: cannot release from detached HEAD." >&2
    exit 1
fi
git -C "$APP_ROOT" diff --quiet "origin/$BRANCH...HEAD" || {
    echo "Error: local branch differs from origin/$BRANCH; push it first." >&2
    exit 1
}

git -C "$APP_ROOT" tag -a "$TAG" -m "Firmware $TAG"
git -C "$APP_ROOT" push origin "$TAG"
echo "Pushed $TAG; GitHub Actions will build and publish the release."
